// Code generated by wazero-emscripten-embind, DO NOT EDIT.
package generated

import "github.com/jerbob92/wazero-emscripten-embind"

func Attach(e embind.Engine) error {
	if err := e.RegisterConstant("SOME_CONSTANT_1", Constant_SOME_CONSTANT_1); err != nil {
		return err
	}
	if err := e.RegisterConstant("SOME_CONSTANT_10", Constant_SOME_CONSTANT_10); err != nil {
		return err
	}
	if err := e.RegisterConstant("SOME_CONSTANT_11", Constant_SOME_CONSTANT_11); err != nil {
		return err
	}
	if err := e.RegisterConstant("SOME_CONSTANT_12", Constant_SOME_CONSTANT_12); err != nil {
		return err
	}
	if err := e.RegisterConstant("SOME_CONSTANT_13", Constant_SOME_CONSTANT_13); err != nil {
		return err
	}
	if err := e.RegisterConstant("SOME_CONSTANT_14", Constant_SOME_CONSTANT_14); err != nil {
		return err
	}
	if err := e.RegisterConstant("SOME_CONSTANT_15", Constant_SOME_CONSTANT_15); err != nil {
		return err
	}
	if err := e.RegisterConstant("SOME_CONSTANT_2", Constant_SOME_CONSTANT_2); err != nil {
		return err
	}
	if err := e.RegisterConstant("SOME_CONSTANT_3", Constant_SOME_CONSTANT_3); err != nil {
		return err
	}
	if err := e.RegisterConstant("SOME_CONSTANT_4", Constant_SOME_CONSTANT_4); err != nil {
		return err
	}
	if err := e.RegisterConstant("SOME_CONSTANT_5", Constant_SOME_CONSTANT_5); err != nil {
		return err
	}
	if err := e.RegisterConstant("SOME_CONSTANT_6", Constant_SOME_CONSTANT_6); err != nil {
		return err
	}
	if err := e.RegisterConstant("SOME_CONSTANT_7", Constant_SOME_CONSTANT_7); err != nil {
		return err
	}
	if err := e.RegisterConstant("SOME_CONSTANT_8", Constant_SOME_CONSTANT_8); err != nil {
		return err
	}
	if err := e.RegisterConstant("SOME_CONSTANT_9", Constant_SOME_CONSTANT_9); err != nil {
		return err
	}
	if err := e.RegisterClass("map_int__string_", &ClassMap_int__string_{}); err != nil {
		return err
	}
	if err := e.RegisterClass("MyClass", &ClassMyClass{}); err != nil {
		return err
	}
	if err := e.RegisterClass("vector_int_", &ClassVector_int_{}); err != nil {
		return err
	}
	if err := e.RegisterEnum("NewStyle", EnumNewStyle(0)); err != nil {
		return err
	}
	if err := e.RegisterEnum("OldStyle", EnumOldStyle(0)); err != nil {
		return err
	}
	return nil
}
