// Code generated by wazero-emscripten-embind, DO NOT EDIT.
package generated

type EnumNewStyle int32

const (
	EnumNewStyle_ONE EnumNewStyle = 0
	EnumNewStyle_TWO EnumNewStyle = 1
)

func (enum EnumNewStyle) Values() map[string]any {
	return map[string]any{
		"ONE": EnumNewStyle_ONE,
		"TWO": EnumNewStyle_TWO,
	}
}

func (enum EnumNewStyle) Type() any {
	return EnumNewStyle(0)
}

type EnumOldStyle uint32

const (
	EnumOldStyle_ONE EnumOldStyle = 0
	EnumOldStyle_TWO EnumOldStyle = 1
)

func (enum EnumOldStyle) Values() map[string]any {
	return map[string]any{
		"ONE": EnumOldStyle_ONE,
		"TWO": EnumOldStyle_TWO,
	}
}

func (enum EnumOldStyle) Type() any {
	return EnumOldStyle(0)
}
